export const images = {
    hero_img: require("../images/hero-img.jpg"),
    iceland: require("../images/iceland.jpg"),
    iceland_two: require("../images/iceland-two.jpg"),
    iceland_three: require("../images/iceland-three.jpg"),
    iceland_four: require("../images/iceland-four.jpg"),
    iceland_five: require("../images/iceland-five.jpg"),
    iceland_six: require("../images/iceland-six.jpg"),
    iceland_oneway: require("../images/iceland-oneway.jpg"),
    polar_lights: require("../images/polar-lights.jpg"),
    polar_lightstwo: require("../images/polar-lights-two.jpg"),
    polar_lightsthree: require("../images/polar-lights-three.jpg"),
    polar_lightsfour: require("../images/polar-lights-four.jpg"),
    icebad: require("../images/icebad.jpg"),
    icebad_two: require("../images/icebad-two.jpg"),
    icebad_three: require("../images/icebad-three.jpg"),
    icebad_four: require("../images/icebad-four.jpg"),
    hiking: require("../images/hiking.jpg"),
    hiking_two: require("../images/hiking-two.jpg"),
    hiking_three: require("../images/hiking-three.jpg"),
    hiking_four: require("../images/hiking-four.jpg"),
    hotel: require('../images/hotel.jpg'),
    hotel_v: require("../images/hotel-v.jpg"),
    hotel_h: require("../images/hotel-h.jpg"),
};